sudo: true
language: python

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env:
    - PYTHON_VERSION="2.7"
    - NUMPY_VERSION="1.10.1"
    - SCIPY_VERSION="0.16.0"

notifications:
  slack: colour-science:Y6lPPcN7y53Js94geqUpqsAP

addons:
  apt:
   sources:
      - ubuntu-toolchain-r-test
   packages:
      - libboost-all-dev
      - libopenexr-dev
      - libilmbase-dev

before_install:
  - pwd
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - PACKAGES="python=${PYTHON_VERSION}"
  - PACKAGES="${PACKAGES} numpy"; if [ ${NUMPY_VERSION} ]; then PACKAGES="${PACKAGES}=${NUMPY_VERSION}"; fi
  - PACKAGES="${PACKAGES} scipy"; if [ ${SCIPY_VERSION} ]; then PACKAGES="${PACKAGES}=${SCIPY_VERSION}"; fi
  - wget https://github.com/OpenImageIO/oiio/archive/Release-1.5.21.tar.gz -O /tmp/OpenImageIO-1.5.21.tar.gz
  - tar -xvf /tmp/OpenImageIO-1.5.21.tar.gz
  - cd oiio-Release-1.5.21
  - make
  - cd /home/travis/build/KelSolaar/TravisRamblings

install:
  - conda create --yes --quiet -n colour-demosaicing-test ${PACKAGES} pip setuptools nose
  - source activate colour-demosaicing-test
  - pip install colour-science coverage coveralls flake8 mock==1.0.1
  - sudo cp /home/travis/build/KelSolaar/TravisRamblings/oiio-Release-1.5.21/dist/linux64/bin/* /usr/local/bin/
  - sudo cp /home/travis/build/KelSolaar/TravisRamblings/oiio-Release-1.5.21/dist/linux64/lib/* /usr/local/lib/
  - cp /home/travis/build/KelSolaar/TravisRamblings/oiio-Release-1.5.21/dist/linux64/python/OpenImageIO.so /home/travis/miniconda/envs/colour-demosaicing-test/lib/python2.7/site-packages/

script:
  - flake8 colour_demosaicing
  - nosetests --nocapture --with-doctest --doctest-options=+ELLIPSIS,+NORMALIZE_WHITESPACE --with-coverage --cover-package=colour_demosaicing -exclude-dir=

after_success:
  - coveralls
